### ISSUE TITLE
Great extension, Just want share some of my ideas

### ISSUE THREAD

**Issue by tjx666** [sandipchitale/vscode-extensions-explorer#1]
I used want to make a similar extension manager, which includes following features in https://github.com/tjx666/ideas/blob/main/README.md

- [ ] extension manage
  - [x] open extension repository
  - [x] open extension folder
  - [x] open extensions folder
  - [ ] open extension data folder
  - [ ] filter prerelease extensions
  - [ ] remove uninstalled extensions cache
  - [ ] remove outdate extensions cache
  - [ ] find extensions which support prerelease
  - [ ] uninstall disabled extensions
  - [ ] find extension activationEvents is `*`
  - [ ] vscode-clear-storage https://github.com/ctf0/vscode-clear-storage

feel free to close this issue.

**Comment by sandipchitale** [comment]
I will look into implementing some of these ideas.
